version: "3.3"
services:
  document_consumer:
    build: .
    container_name: document_consumer
    restart: always
    environment:
      - TZ=Europe/Moscow
    env_file:
      - ./source/.env
    networks:
      - uprav_cfu_network
    depends_on:
      - document_db

  document_db:
    image: postgres:16.1-alpine3.18
    container_name: document_db
    restart: always
    env_file:
      - ./.env
    ports:
      - 39455:5432
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    networks:
      - uprav_cfu_network
    volumes:
      - db_data:/var/lib/postgresql/data
    profiles: [update_db]

volumes:
  db_data:

networks:
  uprav_cfu_network:
    external: true
